import KiknadzeKrasnov.GammaMoments
import Mathlib.MeasureTheory.Integral.Gamma

namespace KiknadzeKrasnov

noncomputable section

open Set MeasureTheory
open scoped BigOperators

/-- Gamma integral generated by a pair of distributed vorticity modes after the exact
radial change of variables. -/
def enstrophyKernelIntegral (s B : ℝ) : ℝ :=
  ∫ x in Ioi (0 : ℝ), x ^ (2 * s - 2) * Real.exp (-(B * x))

/-- The pairwise enstrophy kernel is finite and evaluates in closed form precisely on the
paper's admissible branch `s>1/2`, for positive combined inverse scale `B`. -/
theorem enstrophyKernelIntegral_eq
    {s B : ℝ} (hs : (1 / 2 : ℝ) < s) (hB : 0 < B) :
    enstrophyKernelIntegral s B =
      (1 / B) ^ (2 * s - 1) * gammaFn (2 * s - 1) := by
  have ha : 0 < 2 * s - 1 := by linarith
  have h := Real.integral_rpow_mul_exp_neg_mul_Ioi
    (a := 2 * s - 1) (r := B) ha hB
  unfold enstrophyKernelIntegral
  change (∫ x in Ioi (0 : ℝ), x ^ ((2 * s - 1) - 1) * Real.exp (-(B * x))) = _
  simpa [gammaFn] using h

/-- Denominator form used in manuscript Eq. (96). -/
theorem enstrophyKernelIntegral_eq_div
    {s B : ℝ} (hs : (1 / 2 : ℝ) < s) (hB : 0 < B) :
    enstrophyKernelIntegral s B =
      gammaFn (2 * s - 1) / B ^ (2 * s - 1) := by
  rw [enstrophyKernelIntegral_eq hs hB]
  rw [one_div, Real.inv_rpow hB.le]
  field_simp [Real.rpow_pos_of_pos hB (2 * s - 1) |>.ne']

/-- One `(i,j)` contribution to the manuscript multimode enstrophy formula (96). -/
def enstrophyPairClosed
    (circI circJ s betaI betaJ : ℝ) : ℝ :=
  gammaFn (2 * s - 1) / (2 * Real.pi * gammaFn s ^ 2) *
    (circI * circJ * (betaI * betaJ) ^ s /
      (betaI + betaJ) ^ (2 * s - 1))

/-- Closed finite-mode enstrophy from manuscript Eq. (96). -/
def multimodeEnstrophyClosed {n : ℕ}
    (circ : Fin n → ℝ) (s : ℝ) (beta : Fin n → ℝ) : ℝ :=
  ∑ i, ∑ j, enstrophyPairClosed (circ i) (circ j) s (beta i) (beta j)

/-- Single-mode enstrophy from manuscript Eq. (97). -/
def singleModeEnstrophyClosed (circ s beta : ℝ) : ℝ :=
  circ ^ 2 * beta * gammaFn (2 * s - 1) /
    (2 ^ (2 * s) * Real.pi * gammaFn s ^ 2)

/-- The diagonal `(i,i)` term of Eq. (96) reduces exactly to Eq. (97). -/
theorem enstrophyPairClosed_diagonal_eq_single
    {circ s beta : ℝ} (hs : (1 / 2 : ℝ) < s) (hbeta : 0 < beta) :
    enstrophyPairClosed circ circ s beta beta =
      singleModeEnstrophyClosed circ s beta := by
  unfold enstrophyPairClosed singleModeEnstrophyClosed
  have hb : beta ≠ 0 := hbeta.ne'
  have h2b : 0 < 2 * beta := by positivity
  rw [mul_rpow hbeta.le hbeta.le]
  rw [add_self]
  rw [mul_rpow (by positivity : (0 : ℝ) ≤ 2) hbeta.le]
  rw [← Real.rpow_natCast beta 2]
  rw [← Real.rpow_add hbeta.le]
  field_simp [Real.pi_ne_zero, gammaFn_ne_zero (by linarith : 0 < s),
    Real.rpow_pos_of_pos hbeta (2 * s) |>.ne',
    Real.rpow_pos_of_pos h2b (2 * s - 1) |>.ne']
  ring

/-- The convergence threshold in Eq. (96) is algebraically identical to positivity of
`2s-1`, the gamma-integral shape parameter. -/
theorem enstrophy_threshold_iff {s : ℝ} :
    (1 / 2 : ℝ) < s ↔ 0 < 2 * s - 1 := by
  constructor <;> intro h <;> linarith

/-- Eq. (98): because single-mode enstrophy is linear in `beta`, the Riccati scale law
implies `Zdot=(a-4νβ)Z`. -/
theorem singleModeEnstrophy_hasDerivAt
    {circ s nu a betaDot t : ℝ} {beta : ℝ → ℝ}
    (hs : (1 / 2 : ℝ) < s)
    (hbeta : HasDerivAt beta betaDot t)
    (hscale : scaleResidual nu a (beta t) betaDot = 0) :
    HasDerivAt (fun tau => singleModeEnstrophyClosed circ s (beta tau))
      ((a - 4 * nu * beta t) * singleModeEnstrophyClosed circ s (beta t)) t := by
  have hb := scaleResidual_zero_iff.mp hscale
  unfold singleModeEnstrophyClosed
  have hconst := hbeta.const_mul
    (circ ^ 2 * gammaFn (2 * s - 1) /
      (2 ^ (2 * s) * Real.pi * gammaFn s ^ 2))
  convert hconst using 1
  · funext tau
    ring
  · rw [hb]
    ring

end

end KiknadzeKrasnov
